language: node_js

node_js:
  - "8"
  - "4.3.2"

addons:
  postgresql: "9.4"

env:
  TEST_PG_URL: postgres://localhost:5432/travis

cache:
  directories:
    - node_modules
    - $NVM_DIR

script:
  - scripts/ci

matrix:
  include:
    - addons:
        postgresql: 9.5
      sudo: required
      dist: trusty
